# Generated by Django 2.1.3 on 2018-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(editable=False, max_length=44, unique=True),
        ),
    ]
