# Generated by Django 2.1.3 on 2018-11-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181104_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='report_fields',
            new_name='report_form',
        ),
        migrations.RenameField(
            model_name='bounty',
            old_name='signup_fields',
            new_name='signup_form',
        ),
    ]
