# Generated by Django 2.1.3 on 2018-11-05 05:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181105_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
