# Generated by Django 2.1.3 on 2018-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181105_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='description',
            field=models.TextField(),
        ),
    ]
