# Generated by Django 2.1.3 on 2018-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181105_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
